###
# #%L
# wsdlit
# %%
# Copyright (C) 2021 - 2023 Axencia para a Modernización Tecnolóxica de Galicia (AMTEGA) - Xunta de Galicia
# %%
# This file is part of "wsdlit".
#
# "wsdlit" is free software: you can redistribute it and/or modify
# it under the terms of:
# European Union Public License, either Version 1.2 or – as soon
# they will be approved by the European Commission - subsequent versions of
# the EUPL;
#
# "wsdlit" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# European Union Public License for more details.
#
# You may obtain a copy of tce European Union Public Licence at:
# http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
# #L%
###

name: Cross build
on:
    workflow_run:
        branches: [ main ]
        types:
            - completed
        workflows: [ build ]

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'macOS-latest' ]
        java: [ '8', '11' ]
        maven: [ '3.8.7', '3.9.0', '4.0.0-alpha-3' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Prepare build
        shell: bash
        run: ${PWD}/bin/prepare-build.sh

      - name: Setup Java / Maven
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-distribution: 'zulu'
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
          cache-path: ~/.m2/repository
          cache-prefix: wsdlit-cross-build-

      - name: Build with Maven
        shell: bash
        run: mvn clean package
